server:
  port: 4200 #Gateway port

spring:
  cloud:
    gateway:
      routes:
        - id: auth=service-route
          # auth-ecs-service-123423432.aws.com
          uri: http://host.docker.internal:4300
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
            - JwtValidation

        - id: api-docs-auth-route
          uri: http://host.docker.internal:4300
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs