### POST request to create patient
POST http://lb-28e221d3.elb.localhost.localstack.cloud:4200/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Will Smith with kafka consumer",
  "email": "will.smith_kafka_consumer@example.com",
  "address": "5232 Cambridge Street",
  "dateOfBirth": "1957-06-02",
  "registeredDate": "2025-05-01",
  "driverLicense": "32953714"
}

###